/**
 * Prints `presets/colors.generated.ts`: every Base, Accent and shared Colour Role as hex, converted
 * from the oklch in `presets/source.ts`. Run it through the package script, which also formats:
 *
 *   pnpm --filter ui generate:preset-colors
 *
 * Uses no Node APIs (output goes to stdout) so it runs with plain `node` type stripping.
 */
import { generatePresetColors } from "../presets/generate.ts";

const { base, accent, shared, adjustments } = generatePresetColors();
const json = (value: unknown) => JSON.stringify(value, null, 2);

console.log(`// GENERATED by packages/ui/scripts/generate-preset-colors.ts from presets/source.ts.
// Do not edit by hand: change the source or generator and run \`pnpm --filter ui generate:preset-colors\`.
import type {
  AccentColor,
  AccentColourRoles,
  BaseColor,
  BaseColourRoles,
  ContrastAdjustment,
  SchemeName,
  SharedColourRoles,
} from "./types.ts";

/** The neutral Colour Roles of each Base Colour. */
export const BASE_COLOR_VALUES: Record<BaseColor, Record<SchemeName, BaseColourRoles>> = ${json(base)};

/** \`primary\`, \`primaryForeground\` and \`ring\` of each Accent Colour. */
export const ACCENT_COLOR_VALUES: Record<AccentColor, Record<SchemeName, AccentColourRoles>> = ${json(accent)};

/** Status Colour Roles and \`overlay\`, the same in every Preset. */
export const SHARED_COLOR_VALUES: Record<SchemeName, SharedColourRoles> = ${json(shared)};

/** Foregrounds whose upstream value missed WCAG AA (4.5:1) and were nudged in oklch lightness. */
export const CONTRAST_ADJUSTMENTS: readonly ContrastAdjustment[] = ${json(adjustments)};`);
