// Generated by scripts/generate-index.ts from packages/ui _registry.ts files. Do not edit.
// Regenerate with `pnpm --filter showcase generate:index`.

export type RegistryIndexEntry = {
  type: string;
  description: string;
  load: () => Promise<Record<string, unknown>>;
};

export const registryIndex: Record<string, RegistryIndexEntry> = {
  announce: {
    type: "registry:lib",
    description:
      "Reliable screen-reader announcements on iOS and Android (Button and Input status, Toast).",
    load: () => import("@/registry/utils/announce"),
  },
  button: {
    type: "registry:ui",
    description:
      "Button with Variants (primary, secondary, outline, ghost, destructive, link), Sizes, an icon slot, loading and status; icon-only requires aria-label.",
    load: () => import("@/registry/components/button"),
  },
  container: {
    type: "registry:ui",
    description:
      "Wraps a Screen: safe-area edges, scrolling, keyboard avoidance, Token padding and a max content width.",
    load: () => import("@/registry/components/container"),
  },
  "focus-chain": {
    type: "registry:ui",
    description: "Automatic Next/Done between fields in on-screen order; Done submits the form.",
    load: () => import("@/registry/components/primitives/focus-chain"),
  },
  "form-field-context": {
    type: "registry:ui",
    description:
      "Links a field to its label, description and error for screen readers; passes status, disabled and required down.",
    load: () => import("@/registry/components/primitives/form-field-context"),
  },
  icon: {
    type: "registry:ui",
    description:
      "Every glyph: a Lucide icon at a Token size in a Colour Role, decorative unless labelled.",
    load: () => import("@/registry/components/icon"),
  },
  keyboard: {
    type: "registry:ui",
    description:
      "KeyboardProvider setup, a scroll view that keeps the focused field above the keyboard, and a footer that keeps a form's main button above it.",
    load: () => import("@/registry/components/primitives/keyboard"),
  },
  portal: {
    type: "registry:ui",
    description:
      "Renders content above every Screen (above native modals on iOS), layered and safe-area aware.",
    load: () => import("@/registry/components/primitives/portal"),
  },
  pressable: {
    type: "registry:ui",
    description:
      "Pressed look from a Style Slot, tap area extended to 48, no handlers while disabled or loading, optional haptics, role and aria-* states.",
    load: () => import("@/registry/components/primitives/pressable"),
  },
  "selection-group": {
    type: "registry:ui",
    description:
      "Single or multiple choice within a group, with radio, tab or checkbox roles and selected states.",
    load: () => import("@/registry/components/primitives/selection-group"),
  },
  text: {
    type: "registry:ui",
    description:
      "All text: the type ramp as Variants, text Colour Roles, alignment and the font-scaling switch.",
    load: () => import("@/registry/components/text"),
  },
  theme: {
    type: "registry:lib",
    description:
      "Tokens, Scale, Colour Roles, ThemeProvider, createStyles and the navigation theme.",
    load: () => import("@/registry/theme"),
  },
  "use-controllable-state": {
    type: "registry:hook",
    description: "One implementation of controlled and uncontrolled values for form controls.",
    load: () => import("@/registry/hooks/use-controllable-state"),
  },
};
