// Generated by scripts/generate-index.ts from packages/ui _registry.ts files. Do not edit.
// Regenerate with `pnpm --filter showcase generate:index`.

export type RegistryIndexEntry = {
  type: string;
  description: string;
  load: () => Promise<Record<string, unknown>>;
};

export const registryIndex: Record<string, RegistryIndexEntry> = {
  "focus-chain": {
    type: "registry:ui",
    description: "Automatic Next/Done between fields in on-screen order; Done submits the form.",
    load: () => import("@/registry/components/primitives/focus-chain"),
  },
  "form-field-context": {
    type: "registry:ui",
    description:
      "Links a field to its label, description and error for screen readers; passes status, disabled and required down.",
    load: () => import("@/registry/components/primitives/form-field-context"),
  },
  keyboard: {
    type: "registry:ui",
    description:
      "KeyboardProvider setup, a scroll view that keeps the focused field above the keyboard, and a footer that keeps a form's main button above it.",
    load: () => import("@/registry/components/primitives/keyboard"),
  },
  portal: {
    type: "registry:ui",
    description:
      "Renders content above every Screen (above native modals on iOS), layered and safe-area aware.",
    load: () => import("@/registry/components/primitives/portal"),
  },
  pressable: {
    type: "registry:ui",
    description:
      "Pressed look from a Style Slot, tap area extended to 48, no handlers while disabled or loading, optional haptics, role and aria-* states.",
    load: () => import("@/registry/components/primitives/pressable"),
  },
  "selection-group": {
    type: "registry:ui",
    description:
      "Single or multiple choice within a group, with radio, tab or checkbox roles and selected states.",
    load: () => import("@/registry/components/primitives/selection-group"),
  },
  theme: {
    type: "registry:lib",
    description:
      "Tokens, Scale, Colour Roles, ThemeProvider, createStyles and the navigation theme.",
    load: () => import("@/registry/theme"),
  },
  "use-controllable-state": {
    type: "registry:hook",
    description: "One implementation of controlled and uncontrolled values for form controls.",
    load: () => import("@/registry/hooks/use-controllable-state"),
  },
};
