// Generated by scripts/generate-index.ts from packages/ui _registry.ts files. Do not edit.
// Regenerate with `pnpm --filter showcase generate:index`.

export type RegistryIndexEntry = {
  type: string;
  description: string;
  load: () => Promise<Record<string, unknown>>;
};

export const registryIndex: Record<string, RegistryIndexEntry> = {
  alert: {
    type: "registry:ui",
    description:
      "Alert, AlertTitle and AlertDescription: an inline message with Variants (default, destructive, success, warning, info), each with a default icon.",
    load: () => import("@/registry/components/alert"),
  },
  "alert-demo": {
    type: "registry:example",
    description: "Alerts in every Variant, and one with a custom icon.",
    load: () => import("@/registry/examples/alert-demo"),
  },
  announce: {
    type: "registry:lib",
    description:
      "Reliable screen-reader announcements on iOS and Android (Button and Input status, Toast).",
    load: () => import("@/registry/utils/announce"),
  },
  avatar: {
    type: "registry:ui",
    description: "Round user image (expo-image) with fallback initials, in sizes sm, md and lg.",
    load: () => import("@/registry/components/avatar"),
  },
  "avatar-demo": {
    type: "registry:example",
    description: "Avatars in every size, with an image and with initials only.",
    load: () => import("@/registry/examples/avatar-demo"),
  },
  badge: {
    type: "registry:ui",
    description:
      "Small status label with Variants default, secondary, outline, destructive, success and warning.",
    load: () => import("@/registry/components/badge"),
  },
  "badge-demo": {
    type: "registry:example",
    description: "A Badge in every Variant.",
    load: () => import("@/registry/examples/badge-demo"),
  },
  button: {
    type: "registry:ui",
    description:
      "Button with Variants (primary, secondary, outline, ghost, destructive, link), Sizes, an icon slot, loading and status; icon-only requires aria-label.",
    load: () => import("@/registry/components/button"),
  },
  card: {
    type: "registry:ui",
    description:
      "Card surface with CardHeader, CardTitle, CardDescription, CardContent and CardFooter; onPress makes the whole card pressable.",
    load: () => import("@/registry/components/card"),
  },
  "card-demo": {
    type: "registry:example",
    description: "A Card with header, content and footer, and a pressable Card.",
    load: () => import("@/registry/examples/card-demo"),
  },
  checkbox: {
    type: "registry:ui",
    description:
      "Checkbox with an optional label, controlled or uncontrolled, an indeterminate (mixed) state and a haptic tick.",
    load: () => import("@/registry/components/checkbox"),
  },
  "checkbox-demo": {
    type: "registry:example",
    description:
      "A labelled Checkbox, a 'select all' with an indeterminate state, and a disabled one.",
    load: () => import("@/registry/examples/checkbox-demo"),
  },
  chip: {
    type: "registry:ui",
    description:
      "Chip (plain, toggle or removable, with an optional icon) and ChipGroup (single or multiple choice on the SelectionGroup Primitive), with a haptic tick.",
    load: () => import("@/registry/components/chip"),
  },
  "chip-demo": {
    type: "registry:example",
    description: "Single and multiple ChipGroups, a toggle Chip with an icon and removable Chips.",
    load: () => import("@/registry/examples/chip-demo"),
  },
  container: {
    type: "registry:ui",
    description:
      "Wraps a Screen: safe-area edges, scrolling, keyboard avoidance, Token padding and a max content width.",
    load: () => import("@/registry/components/container"),
  },
  "empty-state": {
    type: "registry:ui",
    description:
      "What a Screen or list shows when there is nothing to show yet: an icon, a title, a description and an action.",
    load: () => import("@/registry/components/empty-state"),
  },
  "empty-state-demo": {
    type: "registry:example",
    description: "An empty inbox with a New message action.",
    load: () => import("@/registry/examples/empty-state-demo"),
  },
  "focus-chain": {
    type: "registry:ui",
    description: "Automatic Next/Done between fields in on-screen order; Done submits the form.",
    load: () => import("@/registry/components/primitives/focus-chain"),
  },
  "form-field": {
    type: "registry:ui",
    description:
      'Lays out a control with its Label, description and error, and links them for screen readers ("Email, text field, Enter a valid email").',
    load: () => import("@/registry/components/form-field"),
  },
  "form-field-context": {
    type: "registry:ui",
    description:
      "Links a field to its label, description and error for screen readers; passes status, disabled and required down.",
    load: () => import("@/registry/components/primitives/form-field-context"),
  },
  "form-field-demo": {
    type: "registry:example",
    description: "Email and password fields in a FocusChain, with a description and an error.",
    load: () => import("@/registry/examples/form-field-demo"),
  },
  icon: {
    type: "registry:ui",
    description:
      "Every glyph: a Lucide icon at a Token size in a Colour Role, decorative unless labelled.",
    load: () => import("@/registry/components/icon"),
  },
  input: {
    type: "registry:ui",
    description:
      "Single-line text field with Sizes, a leading icon, error/success status, a focus ring and an automatic Show/Hide password toggle.",
    load: () => import("@/registry/components/input"),
  },
  "input-demo": {
    type: "registry:example",
    description: "Inputs with an icon, Sizes, a status and a password toggle.",
    load: () => import("@/registry/examples/input-demo"),
  },
  keyboard: {
    type: "registry:ui",
    description:
      "KeyboardProvider setup, a scroll view that keeps the focused field above the keyboard, and a footer that keeps a form's main button above it.",
    load: () => import("@/registry/components/primitives/keyboard"),
  },
  label: {
    type: "registry:ui",
    description:
      'A field\'s visible label in the label type Variant, with a required marker read as "required".',
    load: () => import("@/registry/components/label"),
  },
  "label-demo": {
    type: "registry:example",
    description: "A Label and a required Label.",
    load: () => import("@/registry/examples/label-demo"),
  },
  list: {
    type: "registry:ui",
    description:
      "Settings-style rows: ListSection, ListSectionHeader, ListSectionFooter and ListItem (title, description, icon, trailing, chevron, destructive, onPress); FlashList-safe.",
    load: () => import("@/registry/components/list"),
  },
  "list-demo": {
    type: "registry:example",
    description:
      "A settings list: header, footer, icons, trailing values, chevrons and a destructive row.",
    load: () => import("@/registry/examples/list-demo"),
  },
  portal: {
    type: "registry:ui",
    description:
      "Renders content above every Screen (above native modals on iOS), layered and safe-area aware.",
    load: () => import("@/registry/components/primitives/portal"),
  },
  pressable: {
    type: "registry:ui",
    description:
      "Pressed look from a Style Slot, tap area extended to 48, no handlers while disabled or loading, optional haptics, role and aria-* states.",
    load: () => import("@/registry/components/primitives/pressable"),
  },
  progress: {
    type: "registry:ui",
    description:
      "A horizontal progress bar: a value 0–100 that animates, or indeterminate; role progressbar with its value.",
    load: () => import("@/registry/components/progress"),
  },
  "progress-demo": {
    type: "registry:example",
    description: "A determinate bar that fills up, and an indeterminate one.",
    load: () => import("@/registry/examples/progress-demo"),
  },
  "radio-group": {
    type: "registry:ui",
    description:
      "RadioGroup and RadioGroupItem: a single choice from a list on the SelectionGroup Primitive, vertical or horizontal, with a haptic tick.",
    load: () => import("@/registry/components/radio-group"),
  },
  "radio-group-demo": {
    type: "registry:example",
    description: "A vertical and a horizontal RadioGroup, with a disabled item.",
    load: () => import("@/registry/examples/radio-group-demo"),
  },
  "scheme-switcher": {
    type: "registry:ui",
    description:
      "Theme switcher / dark mode toggle: System, Light and Dark as SegmentedTabs, or one icon button cycling through them. Calls setScheme, which persists the choice.",
    load: () => import("@/registry/components/scheme-switcher"),
  },
  "scheme-switcher-demo": {
    type: "registry:example",
    description: "The segmented and icon Variants, sharing the persisted Scheme.",
    load: () => import("@/registry/examples/scheme-switcher-demo"),
  },
  "search-field": {
    type: "registry:ui",
    description:
      "Search box with a search icon, an automatic clear (×) button, a loading spinner and onSubmit from the keyboard's Search key.",
    load: () => import("@/registry/components/search-field"),
  },
  "search-field-demo": {
    type: "registry:example",
    description: "A controlled SearchField with loading and onSubmit.",
    load: () => import("@/registry/examples/search-field-demo"),
  },
  "segmented-tabs": {
    type: "registry:ui",
    description:
      "In-screen tabs (not navigation): segmented or underline Variants, an animated indicator, and only the selected tab's content rendered.",
    load: () => import("@/registry/components/segmented-tabs"),
  },
  "segmented-tabs-demo": {
    type: "registry:example",
    description: "Uncontrolled segmented tabs with icons, and controlled underline tabs.",
    load: () => import("@/registry/examples/segmented-tabs-demo"),
  },
  "selection-group": {
    type: "registry:ui",
    description:
      "Single or multiple choice within a group, with radio, tab or checkbox roles and selected states.",
    load: () => import("@/registry/components/primitives/selection-group"),
  },
  separator: {
    type: "registry:ui",
    description: "A hairline divider, horizontal or vertical, decorative by default.",
    load: () => import("@/registry/components/separator"),
  },
  "separator-demo": {
    type: "registry:example",
    description: "Horizontal and vertical Separators.",
    load: () => import("@/registry/examples/separator-demo"),
  },
  skeleton: {
    type: "registry:ui",
    description:
      "A placeholder shape shown while content loads; pulses unless Reduce Motion is on, hidden from screen readers.",
    load: () => import("@/registry/components/skeleton"),
  },
  "skeleton-demo": {
    type: "registry:example",
    description: "A list row while it loads: an avatar circle and two lines.",
    load: () => import("@/registry/examples/skeleton-demo"),
  },
  spinner: {
    type: "registry:ui",
    description:
      "An indeterminate loading indicator in a Colour Role, announced as busy; still under Reduce Motion.",
    load: () => import("@/registry/components/spinner"),
  },
  "spinner-demo": {
    type: "registry:example",
    description: "Spinners in each size, a Colour Role and a specific name.",
    load: () => import("@/registry/examples/spinner-demo"),
  },
  switch: {
    type: "registry:ui",
    description:
      "A themed on/off Switch, identical on iOS and Android, with an optional label, a thumb that slides (instant under Reduce Motion) and a haptic tick.",
    load: () => import("@/registry/components/switch"),
  },
  "switch-demo": {
    type: "registry:example",
    description: "A controlled Switch with a label, an uncontrolled one and a disabled one.",
    load: () => import("@/registry/examples/switch-demo"),
  },
  "tab-navigation": {
    type: "registry:ui",
    description:
      "The bottom tab bar: the custom tabBar of an Expo Router JS Tabs Layout, with classic and floating Variants, per-tab icons and badges from Tabs.Screen options.",
    load: () => import("@/registry/components/tab-navigation"),
  },
  "tab-navigation-demo": {
    type: "registry:example",
    description:
      "A tabs Layout using TabNavigation (floating) as the tabBar of Expo Router's JS Tabs, with icons and a badge.",
    load: () => import("@/registry/examples/tab-navigation-demo"),
  },
  text: {
    type: "registry:ui",
    description:
      "All text: the type ramp as Variants, text Colour Roles, alignment and the font-scaling switch.",
    load: () => import("@/registry/components/text"),
  },
  textarea: {
    type: "registry:ui",
    description:
      "Multi-line text field that grows from minRows to maxRows, with a character counter when maxLength is set.",
    load: () => import("@/registry/components/textarea"),
  },
  "textarea-demo": {
    type: "registry:example",
    description: "A Textarea with a character counter inside a FormField.",
    load: () => import("@/registry/examples/textarea-demo"),
  },
  theme: {
    type: "registry:lib",
    description:
      "Tokens, Scale, Colour Roles, ThemeProvider, createStyles and the navigation theme.",
    load: () => import("@/registry/theme"),
  },
  toast: {
    type: "registry:ui",
    description:
      "Sonner-style Toasts: a <Toaster /> in the root Layout and toast(), toast.success/error/info/warning/dismiss. At most 3 stacked, 4s auto-dismiss, swipe away, announced, above native modals.",
    load: () => import("@/registry/components/toast"),
  },
  "toast-demo": {
    type: "registry:example",
    description: "Each Toast Variant, a description and an action.",
    load: () => import("@/registry/examples/toast-demo"),
  },
  "use-controllable-state": {
    type: "registry:hook",
    description: "One implementation of controlled and uncontrolled values for form controls.",
    load: () => import("@/registry/hooks/use-controllable-state"),
  },
  "use-motion": {
    type: "registry:hook",
    description:
      "Enter/exit animations and timing/spring configs from the motion Tokens; instant when Reduce Motion is on.",
    load: () => import("@/registry/hooks/use-motion"),
  },
};
