// Generate src/registry-index.ts: every built Registry Item (from packages/ui `_registry.ts`
// files, loaded and validated by the Registry build) mapped to a lazy import of its source.
// Usage: node scripts/generate-index.ts [--check]
//   --check  exit 1 if the committed index is out of date (run by `lint`, so CI catches drift).
import fs from "node:fs";
import path from "node:path";

import { format, resolveConfig } from "prettier";

import { loadItems } from "../../../packages/ui/scripts/registry/build.ts";

import { callbackProps } from "./callback-props.ts";

const APP = path.resolve(import.meta.dirname, "..");
const UI = path.resolve(APP, "..", "..", "packages", "ui");
const OUT = path.join(APP, "src", "registry-index.ts");

/** The file a lazy import loads: the item's `index` file if it has one, else its first source file. */
function entryFile(files: { path: string }[]): string | undefined {
  const sources = files.map((f) => f.path).filter((p) => /\.(ts|tsx)$/.test(p));
  return sources.find((p) => /(^|\/)index\.tsx?$/.test(p)) ?? sources[0];
}

const items = (await loadItems(UI)).sort((a, b) => a.name.localeCompare(b.name));

const entries = items.flatMap((item) => {
  const file = entryFile(item.files ?? []);
  if (!file) return [];
  const specifier = `@/registry/${file.replace(/(\/index)?\.(ts|tsx)$/, "")}`;
  const meta = (item.meta ?? {}) as {
    kind?: string;
    component?: string;
    examples?: string[];
    a11y?: string[];
  };
  const fields: Record<string, unknown> = {
    type: item.type,
    title: item.title ?? item.name,
    description: item.description ?? item.title ?? "",
    kind: meta.kind ?? "",
    category: item.categories?.[0] ?? "",
    examples: meta.examples ?? [],
    a11y: meta.a11y ?? [],
    uses: item.registryDependencies ?? [],
  };
  if (meta.component) {
    fields.component = meta.component;
    fields.callbacks = callbackProps(fs.readFileSync(path.join(UI, file), "utf8"), meta.component);
  }
  const props = Object.entries(fields).map(([k, v]) => `${k}: ${JSON.stringify(v)},`);
  return [
    `${JSON.stringify(item.name)}: { ${props.join(" ")} module: ${JSON.stringify(specifier)}, load: () => import(${JSON.stringify(specifier)}) },`,
  ];
});

const raw = `// Generated by scripts/generate-index.ts from packages/ui _registry.ts files. Do not edit.
// Regenerate with \`pnpm --filter showcase generate:index\`.

export type RegistryIndexEntry = {
  /** The Registry item type, e.g. \`registry:ui\`, \`registry:block\`, \`registry:example\`. */
  type: string;
  title: string;
  description: string;
  /** \`meta.kind\`: Component, Block, Primitive, Theme or Helper ("" for examples). */
  kind: string;
  /** The first category, e.g. \`forms\` or \`feedback\`. */
  category: string;
  /** The item's usage examples (\`meta.examples\`), themselves items in this index. */
  examples: string[];
  /** Accessibility facts (\`meta.a11y\`). */
  a11y: string[];
  /** The items it is built on (\`registryDependencies\`). */
  uses: string[];
  /** The component a Block exports (\`meta.component\`). */
  component?: string;
  /** That component's callback props, read from its Props type. */
  callbacks?: string[];
  /** The module \`load\` imports. */
  module: string;
  load: () => Promise<Record<string, unknown>>;
};

export const registryIndex: Record<string, RegistryIndexEntry> = {
${entries.join("\n")}
};
`;
const source = await format(raw, { ...(await resolveConfig(OUT)), filepath: OUT });

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== source) {
    console.error(
      "src/registry-index.ts is out of date. Run `pnpm --filter showcase generate:index`.",
    );
    process.exit(1);
  }
} else {
  fs.writeFileSync(OUT, source);
  console.log(`Wrote ${entries.length} Registry Items to ${path.relative(process.cwd(), OUT)}`);
}
