// GENERATED by packages/ui/scripts/generate-preset-colors.ts from presets/source.ts.
// Do not edit by hand: change the source or generator and run `pnpm --filter ui generate:preset-colors`.
import type {
  AccentColor,
  AccentColourRoles,
  BaseColor,
  BaseColourRoles,
  ContrastAdjustment,
  SchemeName,
  SharedColourRoles,
} from "./types.ts";

/** The neutral Colour Roles of each Base Colour. */
export const BASE_COLOR_VALUES: Record<BaseColor, Record<SchemeName, BaseColourRoles>> = {
  neutral: {
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#ffffff",
      cardForeground: "#0a0a0a",
      popover: "#ffffff",
      popoverForeground: "#0a0a0a",
      secondary: "#f5f5f5",
      secondaryForeground: "#171717",
      muted: "#f5f5f5",
      mutedForeground: "#707070",
      accent: "#f5f5f5",
      accentForeground: "#171717",
      border: "#e5e5e5",
      input: "#e5e5e5",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#171717",
      cardForeground: "#fafafa",
      popover: "#171717",
      popoverForeground: "#fafafa",
      secondary: "#262626",
      secondaryForeground: "#fafafa",
      muted: "#262626",
      mutedForeground: "#a1a1a1",
      accent: "#262626",
      accentForeground: "#fafafa",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
  stone: {
    light: {
      background: "#ffffff",
      foreground: "#0c0a09",
      card: "#ffffff",
      cardForeground: "#0c0a09",
      popover: "#ffffff",
      popoverForeground: "#0c0a09",
      secondary: "#f5f5f4",
      secondaryForeground: "#1c1917",
      muted: "#f5f5f4",
      mutedForeground: "#776f6a",
      accent: "#f5f5f4",
      accentForeground: "#1c1917",
      border: "#e7e5e4",
      input: "#e7e5e4",
    },
    dark: {
      background: "#0c0a09",
      foreground: "#fafaf9",
      card: "#1c1917",
      cardForeground: "#fafaf9",
      popover: "#1c1917",
      popoverForeground: "#fafaf9",
      secondary: "#292524",
      secondaryForeground: "#fafaf9",
      muted: "#292524",
      mutedForeground: "#a6a09b",
      accent: "#292524",
      accentForeground: "#fafaf9",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
  zinc: {
    light: {
      background: "#ffffff",
      foreground: "#09090b",
      card: "#ffffff",
      cardForeground: "#09090b",
      popover: "#ffffff",
      popoverForeground: "#09090b",
      secondary: "#f4f4f5",
      secondaryForeground: "#18181b",
      muted: "#f4f4f5",
      mutedForeground: "#6e6e78",
      accent: "#f4f4f5",
      accentForeground: "#18181b",
      border: "#e4e4e7",
      input: "#e4e4e7",
    },
    dark: {
      background: "#09090b",
      foreground: "#fafafa",
      card: "#18181b",
      cardForeground: "#fafafa",
      popover: "#18181b",
      popoverForeground: "#fafafa",
      secondary: "#27272a",
      secondaryForeground: "#fafafa",
      muted: "#27272a",
      mutedForeground: "#9f9fa9",
      accent: "#27272a",
      accentForeground: "#fafafa",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
  mauve: {
    light: {
      background: "#ffffff",
      foreground: "#0c090c",
      card: "#ffffff",
      cardForeground: "#0c090c",
      popover: "#ffffff",
      popoverForeground: "#0c090c",
      secondary: "#f3f1f3",
      secondaryForeground: "#1d161e",
      muted: "#f3f1f3",
      mutedForeground: "#79697b",
      accent: "#f3f1f3",
      accentForeground: "#1d161e",
      border: "#e7e4e7",
      input: "#e7e4e7",
    },
    dark: {
      background: "#0c090c",
      foreground: "#fafafa",
      card: "#1d161e",
      cardForeground: "#fafafa",
      popover: "#1d161e",
      popoverForeground: "#fafafa",
      secondary: "#2a212c",
      secondaryForeground: "#fafafa",
      muted: "#2a212c",
      mutedForeground: "#a89ea9",
      accent: "#2a212c",
      accentForeground: "#fafafa",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
  olive: {
    light: {
      background: "#ffffff",
      foreground: "#0c0c09",
      card: "#ffffff",
      cardForeground: "#0c0c09",
      popover: "#ffffff",
      popoverForeground: "#0c0c09",
      secondary: "#f4f4f0",
      secondaryForeground: "#1d1d16",
      muted: "#f4f4f0",
      mutedForeground: "#70705c",
      accent: "#f4f4f0",
      accentForeground: "#1d1d16",
      border: "#e8e8e3",
      input: "#e8e8e3",
    },
    dark: {
      background: "#0c0c09",
      foreground: "#fbfbf9",
      card: "#1d1d16",
      cardForeground: "#fbfbf9",
      popover: "#1d1d16",
      popoverForeground: "#fbfbf9",
      secondary: "#2b2b22",
      secondaryForeground: "#fbfbf9",
      muted: "#2b2b22",
      mutedForeground: "#abab9c",
      accent: "#2b2b22",
      accentForeground: "#fbfbf9",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
  mist: {
    light: {
      background: "#ffffff",
      foreground: "#090b0c",
      card: "#ffffff",
      cardForeground: "#090b0c",
      popover: "#ffffff",
      popoverForeground: "#090b0c",
      secondary: "#f1f3f3",
      secondaryForeground: "#161b1d",
      muted: "#f1f3f3",
      mutedForeground: "#617276",
      accent: "#f1f3f3",
      accentForeground: "#161b1d",
      border: "#e3e7e8",
      input: "#e3e7e8",
    },
    dark: {
      background: "#090b0c",
      foreground: "#f9fbfb",
      card: "#161b1d",
      cardForeground: "#f9fbfb",
      popover: "#161b1d",
      popoverForeground: "#f9fbfb",
      secondary: "#22292b",
      secondaryForeground: "#f9fbfb",
      muted: "#22292b",
      mutedForeground: "#9ca8ab",
      accent: "#22292b",
      accentForeground: "#f9fbfb",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
  taupe: {
    light: {
      background: "#ffffff",
      foreground: "#0c0a09",
      card: "#ffffff",
      cardForeground: "#0c0a09",
      popover: "#ffffff",
      popoverForeground: "#0c0a09",
      secondary: "#f3f1f1",
      secondaryForeground: "#1d1816",
      muted: "#f3f1f1",
      mutedForeground: "#796a64",
      accent: "#f3f1f1",
      accentForeground: "#1d1816",
      border: "#e8e4e3",
      input: "#e8e4e3",
    },
    dark: {
      background: "#0c0a09",
      foreground: "#fbfaf9",
      card: "#1d1816",
      cardForeground: "#fbfaf9",
      popover: "#1d1816",
      popoverForeground: "#fbfaf9",
      secondary: "#2b2422",
      secondaryForeground: "#fbfaf9",
      muted: "#2b2422",
      mutedForeground: "#aba09c",
      accent: "#2b2422",
      accentForeground: "#fbfaf9",
      border: "#ffffff1a",
      input: "#ffffff26",
    },
  },
};

/** `primary`, `primaryForeground` and `ring` of each Accent Colour. */
export const ACCENT_COLOR_VALUES: Record<AccentColor, Record<SchemeName, AccentColourRoles>> = {
  neutral: {
    light: {
      primary: "#171717",
      primaryForeground: "#fafafa",
      ring: "#a1a1a1",
    },
    dark: {
      primary: "#e5e5e5",
      primaryForeground: "#171717",
      ring: "#737373",
    },
  },
  stone: {
    light: {
      primary: "#1c1917",
      primaryForeground: "#fafaf9",
      ring: "#a6a09b",
    },
    dark: {
      primary: "#e7e5e4",
      primaryForeground: "#1c1917",
      ring: "#79716b",
    },
  },
  zinc: {
    light: {
      primary: "#18181b",
      primaryForeground: "#fafafa",
      ring: "#9f9fa9",
    },
    dark: {
      primary: "#e4e4e7",
      primaryForeground: "#18181b",
      ring: "#71717b",
    },
  },
  mauve: {
    light: {
      primary: "#1d161e",
      primaryForeground: "#fafafa",
      ring: "#a89ea9",
    },
    dark: {
      primary: "#e7e4e7",
      primaryForeground: "#1d161e",
      ring: "#79697b",
    },
  },
  olive: {
    light: {
      primary: "#1d1d16",
      primaryForeground: "#fbfbf9",
      ring: "#abab9c",
    },
    dark: {
      primary: "#e8e8e3",
      primaryForeground: "#1d1d16",
      ring: "#7c7c67",
    },
  },
  mist: {
    light: {
      primary: "#161b1d",
      primaryForeground: "#f9fbfb",
      ring: "#9ca8ab",
    },
    dark: {
      primary: "#e3e7e8",
      primaryForeground: "#161b1d",
      ring: "#67787c",
    },
  },
  taupe: {
    light: {
      primary: "#1d1816",
      primaryForeground: "#fbfaf9",
      ring: "#aba09c",
    },
    dark: {
      primary: "#e8e4e3",
      primaryForeground: "#1d1816",
      ring: "#7c6d67",
    },
  },
  amber: {
    light: {
      primary: "#bb4d00",
      primaryForeground: "#fffbeb",
      ring: "#bb4d00",
    },
    dark: {
      primary: "#973c00",
      primaryForeground: "#fffbeb",
      ring: "#973c00",
    },
  },
  blue: {
    light: {
      primary: "#1447e6",
      primaryForeground: "#eff6ff",
      ring: "#1447e6",
    },
    dark: {
      primary: "#193cb8",
      primaryForeground: "#eff6ff",
      ring: "#193cb8",
    },
  },
  cyan: {
    light: {
      primary: "#007595",
      primaryForeground: "#ecfeff",
      ring: "#007595",
    },
    dark: {
      primary: "#005f78",
      primaryForeground: "#ecfeff",
      ring: "#005f78",
    },
  },
  emerald: {
    light: {
      primary: "#007a55",
      primaryForeground: "#ecfdf5",
      ring: "#007a55",
    },
    dark: {
      primary: "#006045",
      primaryForeground: "#ecfdf5",
      ring: "#006045",
    },
  },
  fuchsia: {
    light: {
      primary: "#a800b7",
      primaryForeground: "#fdf4ff",
      ring: "#a800b7",
    },
    dark: {
      primary: "#8a0194",
      primaryForeground: "#fdf4ff",
      ring: "#8a0194",
    },
  },
  green: {
    light: {
      primary: "#008236",
      primaryForeground: "#f0fdf4",
      ring: "#008236",
    },
    dark: {
      primary: "#016630",
      primaryForeground: "#f0fdf4",
      ring: "#016630",
    },
  },
  indigo: {
    light: {
      primary: "#432dd7",
      primaryForeground: "#eef2ff",
      ring: "#432dd7",
    },
    dark: {
      primary: "#372aac",
      primaryForeground: "#eef2ff",
      ring: "#372aac",
    },
  },
  lime: {
    light: {
      primary: "#9ae600",
      primaryForeground: "#35530e",
      ring: "#9ae600",
    },
    dark: {
      primary: "#7ccf00",
      primaryForeground: "#35530e",
      ring: "#7ccf00",
    },
  },
  orange: {
    light: {
      primary: "#ca3500",
      primaryForeground: "#fff7ed",
      ring: "#ca3500",
    },
    dark: {
      primary: "#9f2d00",
      primaryForeground: "#fff7ed",
      ring: "#9f2d00",
    },
  },
  pink: {
    light: {
      primary: "#c6005c",
      primaryForeground: "#fdf2f8",
      ring: "#c6005c",
    },
    dark: {
      primary: "#a3004c",
      primaryForeground: "#fdf2f8",
      ring: "#a3004c",
    },
  },
  purple: {
    light: {
      primary: "#8200db",
      primaryForeground: "#faf5ff",
      ring: "#8200db",
    },
    dark: {
      primary: "#6e11b0",
      primaryForeground: "#faf5ff",
      ring: "#6e11b0",
    },
  },
  red: {
    light: {
      primary: "#c10007",
      primaryForeground: "#fef2f2",
      ring: "#c10007",
    },
    dark: {
      primary: "#9f0712",
      primaryForeground: "#fef2f2",
      ring: "#9f0712",
    },
  },
  rose: {
    light: {
      primary: "#c70036",
      primaryForeground: "#fff1f2",
      ring: "#c70036",
    },
    dark: {
      primary: "#a50036",
      primaryForeground: "#fff1f2",
      ring: "#a50036",
    },
  },
  sky: {
    light: {
      primary: "#0069a8",
      primaryForeground: "#f0f9ff",
      ring: "#0069a8",
    },
    dark: {
      primary: "#00598a",
      primaryForeground: "#f0f9ff",
      ring: "#00598a",
    },
  },
  teal: {
    light: {
      primary: "#00786f",
      primaryForeground: "#f0fdfa",
      ring: "#00786f",
    },
    dark: {
      primary: "#005f5a",
      primaryForeground: "#f0fdfa",
      ring: "#005f5a",
    },
  },
  violet: {
    light: {
      primary: "#7008e7",
      primaryForeground: "#f5f3ff",
      ring: "#7008e7",
    },
    dark: {
      primary: "#5d0ec0",
      primaryForeground: "#f5f3ff",
      ring: "#5d0ec0",
    },
  },
  yellow: {
    light: {
      primary: "#fdc700",
      primaryForeground: "#733e0a",
      ring: "#fdc700",
    },
    dark: {
      primary: "#f0b100",
      primaryForeground: "#733e0a",
      ring: "#f0b100",
    },
  },
};

/** Status Colour Roles and `overlay`, the same in every Preset. */
export const SHARED_COLOR_VALUES: Record<SchemeName, SharedColourRoles> = {
  light: {
    destructive: "#e7000b",
    destructiveForeground: "#fff7f7",
    success: "#008236",
    successForeground: "#f0fdf4",
    warning: "#bb4d00",
    warningForeground: "#fffbeb",
    info: "#0069a8",
    infoForeground: "#f0f9ff",
    overlay: "#00000080",
  },
  dark: {
    destructive: "#ff6467",
    destructiveForeground: "#460809",
    success: "#05df72",
    successForeground: "#032e15",
    warning: "#ffb900",
    warningForeground: "#461901",
    info: "#00bcff",
    infoForeground: "#052f4a",
    overlay: "#000000b3",
  },
};

/** Foregrounds whose upstream value missed WCAG AA (4.5:1) and were nudged in oklch lightness. */
export const CONTRAST_ADJUSTMENTS: readonly ContrastAdjustment[] = [
  {
    ingredient: "base/neutral",
    scheme: "light",
    role: "mutedForeground",
    from: {
      oklch: "oklch(0.556 0 0)",
      hex: "#737373",
      ratio: 4.34,
    },
    to: {
      oklch: "oklch(0.546 0 0)",
      hex: "#707070",
      ratio: 4.54,
    },
  },
  {
    ingredient: "base/stone",
    scheme: "light",
    role: "mutedForeground",
    from: {
      oklch: "oklch(0.553 0.013 58.071)",
      hex: "#79716b",
      ratio: 4.38,
    },
    to: {
      oklch: "oklch(0.548 0.013 58.071)",
      hex: "#776f6a",
      ratio: 4.51,
    },
  },
  {
    ingredient: "base/zinc",
    scheme: "light",
    role: "mutedForeground",
    from: {
      oklch: "oklch(0.552 0.016 285.938)",
      hex: "#71717b",
      ratio: 4.39,
    },
    to: {
      oklch: "oklch(0.542 0.016 285.938)",
      hex: "#6e6e78",
      ratio: 4.58,
    },
  },
  {
    ingredient: "base/olive",
    scheme: "light",
    role: "mutedForeground",
    from: {
      oklch: "oklch(0.58 0.031 107.3)",
      hex: "#7c7c67",
      ratio: 3.85,
    },
    to: {
      oklch: "oklch(0.54 0.031 107.3)",
      hex: "#70705c",
      ratio: 4.57,
    },
  },
  {
    ingredient: "base/mist",
    scheme: "light",
    role: "mutedForeground",
    from: {
      oklch: "oklch(0.56 0.021 213.5)",
      hex: "#67787c",
      ratio: 4.13,
    },
    to: {
      oklch: "oklch(0.54 0.021 213.5)",
      hex: "#617276",
      ratio: 4.51,
    },
  },
  {
    ingredient: "base/taupe",
    scheme: "light",
    role: "mutedForeground",
    from: {
      oklch: "oklch(0.547 0.021 43.1)",
      hex: "#7c6d67",
      ratio: 4.4,
    },
    to: {
      oklch: "oklch(0.537 0.021 43.1)",
      hex: "#796a64",
      ratio: 4.59,
    },
  },
  {
    ingredient: "shared",
    scheme: "light",
    role: "destructiveForeground",
    from: {
      oklch: "oklch(0.971 0.013 17.38)",
      hex: "#fef2f2",
      ratio: 4.36,
    },
    to: {
      oklch: "oklch(0.986 0.013 17.38)",
      hex: "#fff7f7",
      ratio: 4.51,
    },
  },
];
